---

name: generate
on:
  push:

jobs:
  roles:
    name: role
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - role: ansible-role-default
          - role: ansible-role-preferences
          - role: ansible-role-minimal
          - role: ansible-role-version
          - role: ansible-role-default
            options:
              - generate_gitignore: no

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          pip install pre-commit
          cd tests/${{ matrix.config.role }}
          if [ ! -z "${{ matrix.config.options }}" ]; then
          ../../generate.yml
          else
            ../../generate.yml --extra-vars '{ ${{ matrix.config.options | join(,) }} }'
          fi
