---

name: generate
on:
  push:

jobs:
  roles:
    name: role
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - role: ansible-role-default
          - role: ansible-role-preferences
          - role: ansible-role-minimal
          - role: ansible-role-version
          - role: ansible-role-default
            generate_config_file: generate_config.yml

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          pip install pre-commit
          cd tests/${{ matrix.config.role }}
          if [ ! -z "${{ matrix.config.generate_config_file }}" ]; then
            ../../generate.yml
          else
            ../../generate.yml --extra-vars @${{ matrix.config.generate_config_file }}
          fi
